# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 02:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=50, null=True, verbose_name='Key')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Name')),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True, verbose_name='State')),
                ('zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True, verbose_name='Zip')),
                ('phone', localflavor.us.models.PhoneNumberField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('comments', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Comments')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Organizations',
                'verbose_name': 'Organization',
            },
        ),
    ]
