# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 02:57
from __future__ import unicode_literals

import ckeditor.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('call_date', models.DateField(verbose_name='Call Date')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.PositiveIntegerField(verbose_name='PIN')),
                ('caller_id', models.CharField(max_length=20, verbose_name='Caller ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True, verbose_name='State')),
                ('zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True, verbose_name='Zip')),
                ('start', models.TimeField(verbose_name='Start')),
                ('end', models.TimeField(verbose_name='End')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Duration')),
                ('notes', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Notes')),
                ('handraises', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Phone Calls',
                'ordering': ['-call_date'],
                'verbose_name': 'Phone Call',
            },
        ),
        migrations.AlterUniqueTogether(
            name='phonecall',
            unique_together=set([('call_date', 'email', 'start', 'end', 'duration')]),
        ),
    ]
