# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 02:56
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, verbose_name='Key')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('ordering', models.PositiveSmallIntegerField(verbose_name='Ordering')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['ordering'],
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='First Name')),
                ('preferred_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Preferred Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Last Name')),
                ('suffix', models.CharField(blank=True, max_length=20, null=True, verbose_name='Suffix')),
                ('email', models.EmailField(db_index=True, max_length=250, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('address_1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('address_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address (cont.)')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='City')),
                ('state', localflavor.us.models.USStateField(db_index=True, max_length=2, verbose_name='State')),
                ('zip', localflavor.us.models.USZipCodeField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Zip')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Details')),
                ('facebook_profile', models.URLField(blank=True, null=True, verbose_name='Facebook Profile')),
                ('twitter_profile', models.URLField(blank=True, null=True, verbose_name='Twitter Profile')),
                ('instagram_profile', models.URLField(blank=True, null=True, verbose_name='Instagram Profile')),
                ('reddit_profile', models.URLField(blank=True, null=True, verbose_name='Reddit Profile')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('categories', models.ManyToManyField(blank=True, to='contact.Category', verbose_name='Categories')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'ordering': ['last_name', 'first_name'],
                'verbose_name': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', ckeditor.fields.RichTextField()),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name_plural': 'Notes',
                'ordering': ['contact', 'dt_updated'],
                'verbose_name': 'Note',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True, verbose_name='Key')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
                'verbose_name': 'Organization',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.Organization', verbose_name='Organization'),
        ),
    ]
