# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetitionSigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='City')),
                ('state', localflavor.us.models.USStateField(blank=True, db_index=True, max_length=2, null=True, verbose_name='State')),
                ('zip', localflavor.us.models.USZipCodeField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Zip')),
                ('non_conforming_zip', models.CharField(blank=True, max_length=250, null=True, verbose_name='Non-Conforming Zip')),
                ('dt_signed', models.DateTimeField(verbose_name='Signed')),
            ],
            options={
                'verbose_name': 'Petition Signer',
                'ordering': ['-dt_signed', 'last_name', 'first_name'],
                'verbose_name_plural': 'Petition Signers',
            },
        ),
    ]
