# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 02:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('organization', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('dt_start', models.DateTimeField(db_index=True, verbose_name='Date/Time Starts')),
                ('dt_end', models.DateTimeField(blank=True, null=True, verbose_name='Date/Time Ends')),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('address_1', models.CharField(blank=True, max_length=250, null=True)),
                ('address_2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('attendees', models.ManyToManyField(related_name='attendees', to='contact.Contact')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_contact', to='contact.Contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-dt_start', 'organization'],
            },
        ),
    ]
