# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 02:58
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True, verbose_name='Key')),
                ('category', models.CharField(max_length=100, unique=True, verbose_name='Category')),
                ('ordering', models.PositiveSmallIntegerField(verbose_name='Ordering')),
            ],
            options={
                'ordering': ['ordering'],
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', ckeditor.fields.RichTextField()),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_note_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_note_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'ordering': ['volunteer', 'dt_updated'],
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='First Name')),
                ('preferred_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Preferred Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Last Name')),
                ('suffix', models.CharField(blank=True, max_length=20, null=True, verbose_name='Suffix')),
                ('email', models.EmailField(db_index=True, max_length=250, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('address_1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('address_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address (cont.)')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='City')),
                ('state', localflavor.us.models.USStateField(blank=True, db_index=True, max_length=2, null=True, verbose_name='State')),
                ('zip', localflavor.us.models.USZipCodeField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Zip')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Details')),
                ('dt_signed_petition', models.DateTimeField(blank=True, null=True, verbose_name='Signed Petition')),
                ('date_signed_up', models.DateField(blank=True, null=True, verbose_name='Date Signed Up')),
                ('date_contacted', models.DateField(blank=True, null=True, verbose_name='Date Contacted')),
                ('contacted_by', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contacted By')),
                ('volunteer_commitment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Volunteer Commitment')),
                ('volunteer_other', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Volunteer Other')),
                ('previous_organizing_experience', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Previous Organizing Experience')),
                ('active_in_presidential_primary', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Active in Presidential Primary')),
                ('other_skills', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Other Skills')),
                ('facebook_profile', models.URLField(blank=True, null=True, verbose_name='Facebook Profile')),
                ('twitter_profile', models.URLField(blank=True, null=True, verbose_name='Twitter Profile')),
                ('instagram_profile', models.URLField(blank=True, null=True, verbose_name='Instagram Profile')),
                ('reddit_profile', models.URLField(blank=True, null=True, verbose_name='Reddit Profile')),
                ('volunteer_comments', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Volunteer Comments')),
                ('date_added_to_list', models.DateField(blank=True, null=True, verbose_name='Date Added To List')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('categories', models.ManyToManyField(blank=True, to='volunteer.Category', verbose_name='Categories')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization', verbose_name='Organization')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
            },
        ),
        migrations.CreateModel(
            name='VolunteerActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Key')),
                ('activity_short', models.CharField(max_length=50, unique=True, verbose_name='Activity (Short)')),
                ('activity', models.CharField(max_length=500, unique=True, verbose_name='Activity (Full)')),
                ('ordering', models.PositiveSmallIntegerField(verbose_name='Ordering')),
            ],
            options={
                'ordering': ['ordering'],
                'verbose_name': 'Volunteer Activity',
                'verbose_name_plural': 'Volunteer Activities',
            },
        ),
        migrations.CreateModel(
            name='VolunteerSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Key')),
                ('source', models.CharField(max_length=100, unique=True, verbose_name='Source')),
                ('ordering', models.PositiveSmallIntegerField(verbose_name='Ordering')),
            ],
            options={
                'ordering': ['ordering'],
                'verbose_name': 'Volunteer Source',
                'verbose_name_plural': 'Volunteer Sources',
            },
        ),
        migrations.AddField(
            model_name='volunteer',
            name='sources',
            field=models.ManyToManyField(blank=True, to='volunteer.VolunteerSource', verbose_name='Sources'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_activities',
            field=models.ManyToManyField(blank=True, to='volunteer.VolunteerActivity', verbose_name='Volunteer Activities'),
        ),
        migrations.AddField(
            model_name='note',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Volunteer'),
        ),
    ]
