# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', localflavor.us.models.USZipCodeField(db_index=True, max_length=10, verbose_name='Zip')),
                ('state', localflavor.us.models.USStateField(db_index=True, max_length=2, verbose_name='State')),
                ('city', models.CharField(max_length=250, verbose_name='City')),
                ('county', models.CharField(blank=True, max_length=250, null=True, verbose_name='County')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('long', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Zip Code',
                'verbose_name_plural': 'Zip Codes',
                'ordering': ['zip'],
            },
        ),
    ]
